version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    exclude-paths:
      - ".github/workflows/CI.yaml"
      - ".github/workflows/CI2.yaml"
      - ".github/workflows/CI3_backup.yml"
      - ".github/workflows/CI3backup.yml"
      - ".github/workflows/CI_ChatGPT.yml"
      - ".github/workflows/CI_Gemini.yml"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    exclude-paths:
      - ".github/workflows/CI.yaml"
      - ".github/workflows/CI2.yaml"
      - ".github/workflows/CI3_backup.yml"
      - ".github/workflows/CI3backup.yml"
      - ".github/workflows/CI_ChatGPT.yml"
      - ".github/workflows/CI_Gemini.yml" 
