name: Release Go Binary

#on:
#  push:
#    tags:
#      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            goamd64: v2
          - goos: windows
            goarch: amd64
            goamd64: v2
          - goos: linux
            goarch: arm64

    steps:
      - uses: actions/checkout@v6.0.1
      - name: Build and release binaries
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # Only include goamd64 when defined (i.e. amd64)
          goamd64: ${{ matrix.goamd64 || '' }}
          executable_compression: upx
          goversion: '1.25.3'
          ldflags: -s -w
