name: Go test coverage

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1
    - name: Set up Go
      continue-on-error: true
      uses: actions/setup-go@v6.2.0
      with:
        go-version: '1.25.7'
    - name: Run tests with race detector and coverage
      continue-on-error: true
      run: |
          go test ./... -race -covermode=atomic -coverprofile=coverage.out
    - name: Display test coverage
      continue-on-error: true
      run: go tool cover -func=coverage.out
